### ISSUE TITLE
Problem with wifi-service.jar and services.jar android 8.1

### ISSUE THREAD

**Issue by ale8530** [anestisb/vdexExtractor#9] opened 2018-02-20 17:33 UTC
There are some problems in deodexing these files:

[service.zip](https://github.com/anestisb/vdexExtractor/files/1741169/service.zip)
[wifi-service.zip](https://github.com/anestisb/vdexExtractor/files/1741170/wifi-service.zip)

**Comment by anestisb** [comment] 2018-02-20 19:04
Duplicate of https://github.com/anestisb/vdexExtractor/issues/3

**Closed by anestisb** 2018-02-20 19:04 UTC
Labels: duplicate

**Comment by ale8530** [comment] 2018-02-20 20:00
you are right, sorry :)
